name: Arduino CI Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - 'arduino:avr:uno'
          - 'arduino:avr:mega'
          - 'arduino:avr:nano'
          - 'arduino:avr:leonardo'
          - 'espressif:esp32:esp32'
          
    steps:
         
      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: ${{matrix.board}}# default is arduino:avr:uno
