name: Arduino CI Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - 'arduino:avr:uno'
          - 'arduino:avr:mega'
          - 'arduino:avr:nano'
          - 'arduino:avr:leonardo'
          - 'esp32:esp32:esp32'
          
    steps:
         
      - name: Checkout
        uses: actions/checkout@v3.5.3
         
      - name: Compile Arduino Sketches
        uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: ${{matrix.fqbn}}
