name: Arduino CI Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - 'arduino:avr:uno'
          - 'arduino:avr:mega'
          - 'arduino:avr:nano'
          - 'arduino:avr:leonardo'
          - 'espressif:esp32:esp32'
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      #- name: Install library from GitHub
      #  run: arduino-cli lib install <library-repo>
        
      #- name: Build sketch and run tests
      #  run: |
      #    arduino-cli compile --fqbn ${{matrix.board}} ./examples
      #    #arduino-cli test --fqbn ${{matrix.board}}

      - name: Compile Arduino Examples
        run: |
         cd <directorio_principal_de_los_ejemplos>
         find . -iname "*.ino" -exec arduino-cli compile --fqbn <board_package>:<board_architecture> {} \;
