name: CMake Release
on:
  workflow_dispatch:
jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
         
      - name: Create New Directory to copy the contets
        run: |
          mkdir CMakeRelease
          
      - name: Copy the source code and other files
        run: |
          cp -R ./src ./CMakeRelease |
          cp -R ./examples ./CMakeRelease |
          cp ./LICENSE ./CMakeRelease
          
          
      - name: Remove CMakeLists.txt files
        run: |
          find ./CMakeRelease -name "*.dox" -type f -delete |
          find ./CMakeRelease -name "*.ino" -type f -delete |
          find ./CMakeRelease -name "PSoC" -type d -exec rm -rf {} +
          
      #- name: Deploy to GitHub Pages
      #  if: success()
      #  uses: crazy-max/ghaction-github-pages@v3
      #  with:
      #    target_branch: Arduino
      #    build_dir: ./CMakeRelease
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Show file structure
        run: |
          tree ./CMakeRelease


          
