name: Create Releases
on:
  workflow_dispatch:
jobs:
  CreateArduinoRelease:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
         
      - name: Create New Directory to copy the contets
        run: |
          mkdir ArduinoRelease
          
      - name: Copy the source code and other files
        run: |
          cp -R ./src ./ArduinoRelease |
          cp -R ./examples ./ArduinoRelease |
          cp ./library.properties ./ArduinoRelease |
          cp ./keywords.txt ./ArduinoRelease |
          cp ./LICENSE ./ArduinoRelease
          cp ./README.md ./ArduinoRelease
          
          
      - name: Remove CMakeLists.txt files
        run: |
          find ./ArduinoRelease -name "CMakeLists.txt" -type f -delete |
          find ./ArduinoRelease -name "*.dox" -type f -delete |
          find ./ArduinoRelease -name "Desktop" -type d -exec rm -rf {} + |
          find ./ArduinoRelease -name "PSoC" -type d -exec rm -rf {} +
          
      - name: Deploy Arduino Bramch
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: Arduino
          build_dir: ./ArduinoRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Show file structure
        run: |
          tree ./ArduinoRelease
          
  CreateCMakeRelease:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Create New Directory to copy the contets
        run: |
          mkdir CMakeRelease
          
      - name: Copy the source code and other files
        run: |
          cp -R ./src ./CMakeRelease |
          cp -R ./examples ./CMakeRelease |
          cp ./LICENSE ./CMakeRelease
          cp ./README.md ./CMakeRelease
          cp ./CMakeLists.txt ./CMakeRelease
          
      - name: Remove examples from Desktop subfolder
        run: |
          for i in ` find . -name Desktop ` ; do mv $i/* $i/.. ; done
          
      - name: Remove CMakeLists.txt files
        run: |
          find ./CMakeRelease -name "*.dox" -type f -delete |
          find ./CMakeRelease -name "*.ino" -type f -delete |
          find ./CMakeRelease -name "Desktop" -type d -exec rm -rf {} + |
          find ./CMakeRelease -name "PSoC" -type d -exec rm -rf {} +

      - name: Deploy CMake Bramch
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: CMake
          build_dir: ./CMakeRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Show file structure
        run: |
          tree ./CMakeRelease


          
