name: Create Releases
on:
  workflow_dispatch:
jobs:
  ArduinoRelease:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Create New Directory to copy the contets
        run: |
          mkdir ArduinoRelease
      
      - name: Copy the source code and other files
        run: ls -a 
      
      - name: Copy the source code and other files
        run: |
          cp -R ./src ./ArduinoRelease |
          cp -R ./examples ./ArduinoRelease |
          cp ./.gitignore ./ArduinoRelease |
          cp ./LICENSE ./ArduinoRelease |
          cp ./README.md ./ArduinoRelease |
          cp ./resources/arduino/keywords.txt ./ArduinoRelease |
          cp ./resources/arduino/library.properties ./ArduinoRelease
      
      - name: Remove examples from Arduino subfolder
        run: |
          for i in ` find . -name Arduino ` ; do mv $i/* $i/.. ; done
      
      - name: Remove CMakeLists.txt files
        run: |
          find ./ArduinoRelease -name "CMakeLists.txt" -type f -delete |
          find ./ArduinoRelease -name "*.dox" -type f -delete |
          find ./ArduinoRelease -name "Desktop" -type d -exec rm -rf {} + |
          find ./ArduinoRelease -name "PSoC" -type d -exec rm -rf {} +
      
      - name: Deploy Arduino Bramch
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: ChecheRomo96/CPVector_Arduino
          publish_branch: master
          publish_dir: ./ArduinoRelease
          force_orphan: false
          disable_nojekyll: true
          allow_empty_commit: true
      
      - name: Show file structure
        run: |
          tree ./ArduinoRelease -a
          
  CMakeRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Create New Directory to copy the contets
        run: |
          mkdir CMakeRelease
      
      - name: Copy the source code and other files
        run: |
          cp -R ./src ./CMakeRelease |
          cp -R ./examples ./CMakeRelease |
          cp -R ./tests ./CMakeRelease |
          cp ./.gitignore ./CMakeRelease |
          cp ./LICENSE ./CMakeRelease |
          cp ./README.md ./CMakeRelease |
          cp ./CMakeLists.txt ./CMakeRelease
      
      - name: Remove examples from Desktop subfolder
        run: |
          for i in ` find . -name Desktop ` ; do mv $i/* $i/.. ; done
      
      - name: Remove CMakeLists.txt files
        run: |
          find ./CMakeRelease -name "*.dox" -type f -delete |
          find ./CMakeRelease -name "*.ino" -type f -delete |
          find ./CMakeRelease -name "Desktop" -type d -exec rm -rf {} + |
          find ./CMakeRelease -name "PSoC" -type d -exec rm -rf {} +
      
      - name: Show file structure
        run: |
          tree ./CMakeRelease
      
      - name: Clone CPVector-CMake repo
        run: |
          git clone https://github.com/ChecheRomo96/CPVector-CMake
      
      - name: Replace src folder with new contents
        run: |
          rm -rf ./CPVector-CMake/src |
          cp -r ./CMakeRelease/src ./CPVector-CMake


      - name: Show file structure
        run: |
          tree ./CPVector-CMake/src
      
      - name: Commit and Push
        working-directory: ./CPVector-CMake
        run: |
          find ./CPVector-CMake -name "index.lock"  -type f -delete |
          git config --global user.name "github-actions[bot]" |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" |
          git add . |
          git commit -m "Automated commit from CPVector github action \"CreateReleases.yml\"" 

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          repository: CPVector-CMake
          directory: ./CPVector-CMake


          
