# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Doxygen to Github Pages

on:
  workflow_dispatch:

jobs:
  ArduinoDocsC:
    runs-on: macos-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install tree
        run: brew install tree
        
      - name: Show File Structure
        run: tree -a
           
      - name: Create New Directory to copy the contets
        run: |
          mkdir -p ./DoxyBuild |
          mkdir -p ./docs/Arduino_C
        
      - name: Copy the source code and other files
        run: |
          cp -R ./src ./DoxyBuild |
          cp -R ./examples ./DoxyBuild |
          cp ./LICENSE ./DoxyBuild |
          cp ./README.md ./DoxyBuild |
          cp ./resources/keywords.txt ./DoxyBuild |
          cp ./resources/doxy/Doxyfile ./DoxyBuild |
          cp ./resources/doxy/DoxygenLayout.xml ./DoxyBuild
          
      - name: Remove examples from Arduino subfolder
        run: |
          for i in ` find ./DoxyBuild -name Arduino ` ; do mv $i/* $i/.. ; done
          
      - name: Remove files not needed from the new directory
        run: |
          find ./DoxyBuild -name "CMakeLists.txt" -type f -delete |
          find ./DoxyBuild -name "Desktop" -type d -exec rm -rf {} + |
          find ./DoxyBuild -name "Arduino" -type d -exec rm -rf {} + |
          find ./DoxyBuild -name "PSoC" -type d -exec rm -rf {} +

      - name: Initialize and Update Submodules
        run: |
          git submodule init
          git submodule update
          
      - name: Install Doxygen
        run: brew install doxygen
        
      - name: Install Graphviz
        run: brew install graphviz

      - name: Generate Documentation
        run: doxygen ./DoxyBuild/ArduinoDocs_C.doxy

      - name: Show build structure
        if: always() 
        run: |
          tree -a ./DoxyBuild
          
      - name: Show docs structure
        if: always() 
        run: |
          tree -a ./docs/Arduino_C/html
      
      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/mainDocs/html
          force_orphan: true
          disable_nojekyll: true
